id: P004178
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC395
  title: 'མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་མཆན་འགྲེལ། '
  author: ''
  volumes:
    99ba3c12e55c4ec28d90e5b272e241a2:
      image_group_id: I2PD19656
      title: ''
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
