id: I9A19F24A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:49:02+00:00'
last_modified: '2022-06-07T20:50:21.266609+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC395
  title: 'མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་མཆན་འགྲེལ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    9C22:
      image_group_id: I2PD19656
      title: ''
      total_pages: 246
      order: 1
      base_file: 9C22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
